### ISSUE TITLE
Updating regional_summary call

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#141]
https://github.com/epiforecasts/covid-rt-estimates/blob/305a1cc2531f9a62d571231b0beb3ab1cbacae74/R/update-regional.R#L136

As written doesn't broadcast all errors into the logs which makes debugging difficult.

**Comment by seabbs** [comment]
Example of a silent failure: https://github.com/epiforecasts/covid-rt-estimates/issues/138#issuecomment-734355591

**Comment by joeHickson** [comment]
it's the ftry function that's killing it!
https://github.com/zatonovo/futile.logger/blob/ce7a07afbd378ad24f1bd966ea9af3d19ec4502b/R/logger.R#L239
it is using trycatch not with calling  handlers so warnings are breaking!
RAGE!
also; it turns out I have already fixed it... we just need to figure out how to specify a branch on my fork rather than the master!
https://github.com/zatonovo/futile.logger/pull/96/files
