### ISSUE TITLE
UK UTLA level estimates not always updating

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#206]
I see that the UTLA level estimates haven't updated for the last two days: https://github.com/epiforecasts/covid-rt-estimates/tree/master/subnational/united-kingdom-local/cases/summary

Not clear what may be driving this.

**Comment by joeHickson** [comment]
last nights is still running. It looks like no new data for the previous two days:

2021-08-04 01:43:10 INFO Data has not been updated since last run. If wanting to run again then remove /home/rstudio/covid-rt-estimates/last-update/united-kingdom-local.rds

2021-08-03 07:04:19 INFO Data has not been updated since last run. If wanting to run again then remove /home/rstudio/covid-rt-estimates/last-update/united-kingdom-local.rds
2021-08-03 07:04:19 DEBUG Max date in data - 2021-07-29, last run date from file - 2021-07-29

**Comment by seabbs** [comment]
Are there still two pools of jobs running (hence the run at 1.43 and at 7?) If yes is the 1:43 run from the 3rd causing an issue? 
 
It is now 3 days since the last update so that means at least two days without data which seems a bit surprising given the PHE dashboard (the source) has been updating...

**Comment by joeHickson** [comment]
The log files show two days with no update - extracted above. Note the two different dates - it's just that one got allocated a node much quicker (both queued at midnight).

The covid-r-job is processing no tasks - you can see there are no modified tasks in that pool in the past week. I will delete it to avoid any confusion.

**Comment by seabbs** [comment]
Great!

**Comment by seabbs** [comment]
Closing as updated elsewhere. Setting up external monitoring to check the last data update to flag is this is driven by something else.
