### ISSUE TITLE
Add support for estimates for each subnational area using multiple data sets. 

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#23]
For the global estimates, we currently provide estimates for both cases and deaths. On the sub-national level we also have both these data sources in many cases and it would be useful to easily be able to support.

**Comment by joeHickson** [comment]
it should be fairly quick to extend the directory path to capture this
e.g. ability to replace "cases" with something else in the directory path (add "output_folder"="cases" to region-entity, update run-region-updates to use this)

You could then set up the country multiple times in the region list with the different data sources and configurations 

There's a chance @JAllen42 has hit this very thing in bringing global deaths / cases over to the same processing pattern but he may have hardwired it as a two way toggle.

**Comment by seabbs** [comment]
Sounds like a good solution/idea. On our end, we need to have a careful look at the data to assess if this is a good idea but we have found it useful as a metric (i.e if cases are diverging from deaths and vice versa) in UK monitoring work.

**Comment by seabbs** [comment]
I am going to start looking at this today as we are interested in making public versions of the gov submitted estimates we currently make (as several new data sources are now public (which are similar to but not the same as the confidential sources).

**Comment by joeHickson** [comment]
I'll catch up with @JAllen42 to see where he is up to. He might be able to push a part branch that you can pick up and use.

**Comment by joeHickson** [comment]
I think this can now be done via the dataset entities. Specifying folder_name and/or dataset_folder_name on the entity gives you control over the output:
subnational/[folder name if present or dataset name]/[dataset_folder_name | "cases"]/...

e.g,:
name = uk-hospital-admissions, folder_name = united-kingdom, dataset_folder_name = "hospital_admissions"
results in subnational/united-kingdom/hospital_admissions/...

name = uk-2nd-tier-la, folder_name = "united-kingdom-2nd-tier"
results in subnational/united-kingdom-2nd-tier/cases/...

OR folder_name="united-kingdom/second-tier-authorities" results in subnational/united-kingdom/second-tier-authorities/cases/... 


The folder names don't block inclusion of a / so you can sneak a subfolder in. It's probably worth defining a convention and documenting it in the SMG but I think this issue is technically possible now.

**Comment by seabbs** [comment]
Yes that all makes sense - great stuff! 

Could you add the above example to the SMG to make that clear?
