### ISSUE TITLE
Null values

### ISSUE THREAD

**Issue by hamishgibbs** [epiforecasts/covid-rt-estimates#60]
Working with the summary data: 

`national/deaths/summary/summary_table.csv`

and `rt.csv`, `cases_by_infection.csv`, and `cases_by_report.csv`.

There are null summary values  in `summary_table.csv` and missing +- 20% CI estimates in the other three files. Appears to affect only Papua New Guinea.

This has caused some issues in [rt_vis](https://github.com/hamishgibbs/rt_vis) and [RtD3](https://github.com/epiforecasts/RtD3) (and subsequently the epiforecasts site where RtD3 is implemented). Which are in the process of being fixed. 

We will work on accounting for the possibility of null values in summary estimates but I wanted to raise the issue here in case it is some broader issue.

It looks like Papua New Guinea is currently the shortest time series (10 days) which may or may not have anything to do with the problem.

Thanks!

**Comment by seabbs** [comment]
Hi @hamishgibbs, 

Thanks for opening this. 

I think this is probably an issue linked with timeouts and historic estimates. As you know we recently updated estimates to include a 20% CI and potentially PNG hasn't been updated since this change but is still included in the summary `csv`. 

For now error catching in `RtD3` is probably a good way to go but this does highlight that we need to have more analysis in place on the quality of the estimates in order to flag these sort of issues before they impact downstream users.

**Comment by joeHickson** [comment]
PNG seems to have dropped out the deaths dataset - no deaths data since 2020-08-14.  (https://github.com/epiforecasts/covid-rt-estimates/blob/master/national/deaths/summary/cases_by_report.csv#L8969 )
Is this an issue with the data filtering or the source data?

**Comment by seabbs** [comment]
Filtering as they aren't hitting the lower limit on number of days with reported deaths (14). Option is either exclude (run summary on just latest) or append to historic estimates. Downside of just reporting latest and dropping old is that countries may appear/disappear at what appears to be random which downstream users will not like.
