### ISSUE TITLE
National cases not updated for two days but regional cases updating daily.

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#75]
looks like a bug - again any information in the logs @joeHickson?

**Comment by seabbs** [comment]
Looking at the commit logs the case update just dropped for today. I can't think of any reason for this behaviour really apart from an entire run failing which really shouldn't be the case?

**Comment by joeHickson** [comment]
The case update did not run this morning because it was up to date:
2020-10-12 04:40:21 TRACE last_run file (/home/covid/last-update/cases.rds) exists, loading.
2020-10-12 04:40:21 INFO Data has not been updated since last run. If wanting to run again then remove /home/covid/last-update/cases.rds
2020-10-12 04:40:21 DEBUG Max date in data - 2020-10-08, last run date from file - 2020-10-08

The run on 11th completed at 11:50 ish pm UTC so just got in the days processing

Hopefully #57 should make this easier to visualise - on the 10th only the regional cases got processed from that dataset so I wonder if there were issues with the data source (looking at the git commit history). Once we get azure log analytics sorted it should be much easier to pull these logs!

**Comment by seabbs** [comment]
So it should be the same data source which is why it is odd. Yes sounds good. Still seems to be working now. Perhaps the data pull just failed from the ECDC source.
