### ISSUE TITLE
Add a single csv collating all Rt estimates from everywhere

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#92]
For some downstream users, it may make sense to have a single URL joining all the Rt estimates into a single csv. This should be possible using the framework built in #66, #77, #65. 

Optionally at a later date, this could become the only source published but I think this might confuse end-users as to what is available. 

There are two potential issues with making this collated csv. 1.) When to trigger its compilation in the update cycle and 2. How to delineate  between data sources and geographic areas (+if the current framework as implemented provides enough flexibility to support this).

**Comment by joeHickson** [comment]
this will really exacerbate any latest date variation issues so will need careful handling. I would be tempted to keep the individual data sets still as more searchable.
Triggering this is starting to reach towards suite management. I would be tempted to tackle this when we switch infrastructure and get #65 refactored to work in the parallel scenario.

**Comment by seabbs** [comment]
Agree. Think the sensible plan here is to keep the individual data sets, perhaps forever, but also offer this as an option in the same way as we do in the UK. I can imagine if making a dashboard for example having this format would be a great help. 

Personally, I'd be tempted to get this running soon rather than later as the infrastructure move may take a while. For me it depends how much of a headache it is working out when collation should be triggered.

**Comment by joeHickson** [comment]
Possible solution (for discussion):

Have a new summary list that lives alongside the datasets in dataset-list.R - This is a list of new "summary" objects.
The summary object contains:
- list of dataset names that it requires (in the format dataset/* OR dataset/sublocation)
- details of where to put the results (name, folder location, publication data (if post dataverse), etc)
- incremental update flag (run after every dataset or only once all datasets have completed)

Update collate_estimates to work off this summary object, getting it's summary data from the datasets indicated (filtering if required to only the chosen sublocations) and outputting as defined.

Extend the run-region-update hack to trigger these:
-If the summary is non-incremental and the current location is the last on the given list of dataset locations. (This goes away with new infrastructure as it will be scheduled as a separate job.)
- If the summary is incremental and the current location is in the list.

This allows for summary datasets that are not within a single location / dataset folder (currently it is tied to all datasets within a particular folder) and also for subsets to be summarised.

This could allow for summaries like:
Europe National Cases (subset from global cases)
North America Cases (combine USA & Canada at state/province level)
UK All Types (cases + deaths + hospitalisations)


If this is tackled post- dataverse publication then get the summary data from there (if dataverse is configured) rather than local disk and record the source dataset id's for inclusion in the publication metadata (you can link to the source data used to generate the dataset so might as well point back to the various datasets).

**Comment by joeHickson** [comment]
linking as pre-parallel as this needs fixing for the uk summary to allow this

**Comment by joeHickson** [comment]
I'm going to split this task so the infrastructure for it is separate from the script to summarise as they are two tasks

**Comment by joeHickson** [comment]
removing milestone as all rt from everwhere is not needed pre parallel (but the UK one is - see #116 )
